### ISSUE TITLE
pairwise interaction in light_interaction by groups. 

### ISSUE THREAD

**Issue by asheetal** [mayer79/flashlight#37]
The current implementation of pairwise interaction results in nC2 combinations where N is the number of variables v. Is there a way to create interaction between two groups? For example Group A = (a,b,c,d) and Group B (j,k) . In my case I am not interested in scenarios ab, bc, or jk, but only want to focus on aj, ak etc....

I see an option "by" Not sure if that can accomplish what I seek.

**Comment by mayer79** [comment]
This is currently not possible. What you can do is to use `v` to at least restrict the attention on the union of Group A and B and then filter the resulting data object before plotting.

Here is an example:

```
library(flashlight)
library(ranger)

fit <- ranger(Sepal.Length ~ ., iris)

fl <- flashlight(
  model = fit, data = iris, label = "rf", 
  predict_function = function(mod, X) predict(mod, X)$predictions,
  y = "Sepal.Length"
)

group1 <- c("Sepal.Width", "Petal.Width")
group2 <- c("Species", "Petal.Length")

relevant <- c(outer(group1, group2, FUN = paste, sep = ":"))

inter <- light_interaction(fl, pairwise = TRUE)
inter$data <- subset(inter$data, variable %in% relevant)
plot(inter, fill = "orange")
```

![image](https://user-images.githubusercontent.com/16206095/114079703-cdd3bc80-98aa-11eb-8051-e89917492223.png)

**Comment by asheetal** [comment]
Thanks you. That would work post processing.
